This code is to complete the 1st assignment of python-r-git class.


In [ ]:

#import necessary libraries
import numpy as np
import matplotlib.pyplot as plt

#load data as ECGu.txt in the notebook from the data folder
data = np.loadtxt("data/ECGu.txt")
print(data)

[[-275. -119. -119.]
 [-275. -119. -119.]
 [-275. -118. -121.]
 ...
 [  -4.  -83.   21.]
 [  -9.  -88.   31.]
 [ -16.  -96.   33.]]
